### ISSUE TITLE
is not marked as seriali zable

### ISSUE THREAD

**Issue by quan01994** [dotnetcore/EasyCaching#157]
这个问题在 0.6.0 开始存在
![image](https://user-images.githubusercontent.com/20533465/66697401-dc6a0380-ed07-11e9-9d36-bd3dc00bd54c.png)
这是我的两个项目，
一个是2.2的控制台程序
MiniProgram.ConsoleApp
````xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.2</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="EasyCaching.Redis" Version="0.6.1" />
      <PackageReference Include="EasyCaching.Serialization.Json" Version="0.6.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MiniProgram.ShareLib\MiniProgram.ShareLib.csproj" />
    </ItemGroup>
</Project>
````
一个是 公共库 。
````xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="EasyCaching.Core" Version="0.6.1" />
    </ItemGroup>

</Project>
````
这个是公共库里的一个测试服务 ,具体就是注入一个IEasyCachingProvider 
set 一个class
````csharp 
namespace MiniProgram.ShareLib
{
    public class TestService
    {
        private readonly IEasyCachingProvider _cachingProvider;

        public TestService(IEasyCachingProvider cachingProvider)
        {
            _cachingProvider = cachingProvider;
        }

        public void TestInsert()
        {
            _cachingProvider.Set("123", new TestData(), TimeSpan.FromHours(1));
        }
    }

    public class TestData
    {
        public string Data = "1231";
    }
}
````
这个是我的入口函数，具体就是产生一个容器，调用TestInsert
````csharp
namespace MiniProgram.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var services = new ServiceCollection();

            services.AddEasyCaching(option =>
            {
                option.UseRedis(config =>
                {
                    config.DBConfig.Database = 7;
                    config.DBConfig.AllowAdmin = true;
                    config.DBConfig.Endpoints.Add(new ServerEndPoint("localhost", 6379));
                    config.MaxRdSecond = 0;
                }).WithJson();
            });

            services.AddTransient<TestService>();

            IServiceProvider serviceProvider = services.BuildServiceProvider();

            var testService = serviceProvider.GetService<TestService>();

            testService.TestInsert();
        }
    }
}
````
但是这里就报错了。
````log
Unhandled Exception: System.Runtime.Serialization.SerializationException: Type 'MiniProgram.ShareLib.TestData' in Assembly 'MiniProgram.ShareLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as seriali
zable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)
   at System.Runtime.Serialization.FormatterServices.<>c.<GetSerializableMembers>b__5_0(MemberHolder mh)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter
, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
   at EasyCaching.Core.Serialization.DefaultBinaryFormatterSerializer.Serialize[T](T value)
   at EasyCaching.Redis.DefaultRedisCachingProvider.BaseSet[T](String cacheKey, T cacheValue, TimeSpan expiration)
   at EasyCaching.Core.EasyCachingAbstractProvider.Set[T](String cacheKey, T cacheValue, TimeSpan expiration)
   at MiniProgram.ShareLib.TestService.TestInsert() in D:\RiderProjects\MiniProgram\MiniProgram.ShareLib\TestService.cs:line 17
   at MiniProgram.ConsoleApp.Program.Main(String[] args) in D:\RiderProjects\MiniProgram\MiniProgram.ConsoleApp\Program.cs:line 34

````

他并没有条用 json的序列化程序，而是调用了 BinaryFormatter.Serialize 
这个是为什么，是我哪里配置不对，还是bug

**Comment by catcherwong** [comment]
@quan01994 Thanks for your interest in this project.

Modify the configuration of EasyCaching as follow.

```cs
            services.AddEasyCaching(option =>
            {
                var serializerName = "myjson";

                option.UseRedis(config =>
                {
                    config.DBConfig.Database = 7;
                    config.DBConfig.AllowAdmin = true;
                    config.DBConfig.Endpoints.Add(new ServerEndPoint("localhost", 6379));
                    config.MaxRdSecond = 0;
                    // specify the serializer that you want to use.
                    config.SerializerName = serializerName;
                })
                .WithJson(serializerName);
            });
```

EasyCaching will select the serializer via the following order:

 > SerializerName -> ProviderName -> EasyCachingConstValue.DefaultSerializerName

**Comment by catcherwong** [comment]
Follow this [Chinese document](https://github.com/dotnetcore/EasyCaching/wiki/缓存的序列化) for more information about `Serialization`
