### ISSUE TITLE
DefaultSQLiteCachingProvider - GetAsync - NullReferenceException

### ISSUE THREAD

**Issue by jubba2001** [dotnetcore/EasyCaching#277]
## Description

SQLite Caching Provider is not thread-safe.

The NullReferenceException is raised while inserting same key value more 100 times in parallel:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand command)
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in /_/Dapper/SqlMapper.Async.cs:line 459
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EasyCaching.SQLite.DefaultSQLiteCachingProvider.<BaseGetAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EasyCaching.Core.EasyCachingAbstractProvider.<GetAsync>d__69`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp4.ConsoleHostedService.<StartAsync>d__4.MoveNext() in C:\Users\KGuzenko\source\repos\tests\ConsoleApp4\ConsoleHostedService.cs:line 33
```
This may be happened because of using [the same sqlite db connection across multiple threads](https://github.com/dotnet/efcore/issues/20651)

### Steps to Reproduce

1.  `UseSQLite(config => config.DBConfig = new SQLiteDBOptions { FileName = "my.db" }));`
2.  `GetAsync` the same value from cache in parallel more then 100 times.

### Related code

```
            var tasks = Enumerable.Range(0, 100)
                .AsParallel()
                .AsUnordered()
                .Select(_ => _provider.GetAsync("demo", async () => await Task.FromResult("456"), TimeSpan.FromMinutes(1)))
                .ToArray();

            await Task.WhenAll(tasks);
```

**Expected behavior:** Add value to cache without error :))

**Actual behavior:** NullReferenceException raised.

## Specifications

- Provider    : SQLite (version 1.1.0)
- Interceptor : not use
- Serializer  : not use
- System      : Windows 10

**Comment by catcherwong** [comment]
@jubba2001 Thanks for your interest in this project.

Could you please have a try with the newest preview version, it fixed `same sqlite db connection across multiple threads`.

see #260 .

**Comment by jubba2001** [comment]
@catcherwong, Thank you very match! NullReferenceException is not raised anymore.
