### ISSUE TITLE
UseHybrid with WithRedisBus throws error "Sequence contains no matching element"

### ISSUE THREAD

**Issue by arnoldsi-vii** [dotnetcore/EasyCaching#341]
## Description

When we register EasyCaching with UseHybrid we are getting `Sequence contains no matching element`

### Steps to Reproduce

1. Use simple Example: https://easycaching.readthedocs.io/en/latest/Hybrid/

### Related code

```
 services.AddEasyCaching(options =>
            {
                options.UseInMemory("EasyCacheRedis_Memory");


                Action<JsonSerializerSettings> jsonNET = x =>
                {
                    x.ContractResolver = new JsonIgnoreAttributeIgnorerContractResolver();
                    x.ReferenceLoopHandling = ReferenceLoopHandling.Serialize;
                    x.PreserveReferencesHandling = PreserveReferencesHandling.Objects;
                    x.TypeNameHandling = TypeNameHandling.All;
                };

                options.WithJson(jsonNET, "json.net_setting");

                var redisOptions = new RedisOptions();
                configuration.GetSection("CacheConfig:EasyCaching:Redis").Bind(redisOptions);

                options.UseRedis(config =>
                {
                    config.DBConfig = redisOptions.DBConfig;
                    config.SleepMs = redisOptions.SleepMs;
                    config.MaxRdSecond = redisOptions.MaxRdSecond;
                    config.LockMs = redisOptions.LockMs;
                    config.EnableLogging = redisOptions.EnableLogging;
                    config.CacheNulls = false;
                    config.SerializerName = "json.net_setting";
                }, "EasyCacheRedis_Redis");
              

                options.UseHybrid(config =>
                {
                    config.TopicName = "redis-sync";
                    config.EnableLogging = redisOptions.EnableLogging;


                    // specify the local cache provider name after v0.5.4
                    config.LocalCacheProviderName = "EasyCacheRedis_Memory";
                    // specify the distributed cache provider name after v0.5.4
                    config.DistributedCacheProviderName = "EasyCacheRedis_Redis";
                })
                // use redis bus
                .WithRedisBus(busConf =>
                 {


                     foreach (var endPoint in redisOptions.DBConfig.Endpoints)
                     {
                         busConf.Endpoints.Add(endPoint);
                     }
                 }, "EasyCacheRedis_Redis");

            });

```

**Expected behavior:** 
This should have worked

**Actual behavior:**
Exception:
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at EasyCaching.Bus.Redis.DefaultRedisBus..ctor(String name, IEnumerable`1 subscriberProviders, RedisBusOptions busOptions, IEnumerable`1 serializers)
   at EasyCaching.Bus.Redis.RedisBusOptionsExtension.<AddServices>b__3_1(IServiceProvider x)
```
I investigatedeven more and the issues seems to be resolving `IEasyCachingBus`

## Specifications

- Provider    : InMemory (version 1.5.0), Redis (version 1,5.0)
- Serializer  : Newtonsoft.Json.

**Comment by catcherwong** [comment]
@arnoldsi-vii Thanks for your interest in this project.

We will take a look ASAP.

**Comment by arnoldsi-vii** [comment]
@catcherwong any updates on this?
Thank you

**Comment by catcherwong** [comment]
You forgot to set the `SerializerName` for redis bus.

```cs
.WithRedisBus(busConf =>
                {
                    foreach (var endPoint in redisOptions.DBConfig.Endpoints)
                    {
                        busConf.Endpoints.Add(endPoint);
                    }

                    // set the SerializerName for the bus here !!
                    busConf.SerializerName = "json.net_setting";
                }, "EasyCacheRedis_Redis");
```

**Comment by arnoldsi-vii** [comment]
hmmm,  I'll check
@catcherwong thanks
