### ISSUE TITLE
EasyCaching.Redis AllowAdmin option

### ISSUE THREAD

**Issue by AntonioSCoelho** [dotnetcore/EasyCaching#408]
## Description

How can [`AllowAdmin`](https://stackexchange.github.io/StackExchange.Redis/Configuration.html#configuration-options) option be added? 

### Steps to Reproduce
1) Config

```
services.AddEasyCaching(options =>
{
     options.UseRedis(configuration);
}
```

2) Call `_easyCachingProvider.FlushAsync()` method with EasyCaching.Redis

### Error
```
StackExchange.Redis.RedisCommandException: This operation is not available unless admin mode is enabled: FLUSHDB
   at StackExchange.Redis.ConnectionMultiplexer.CheckMessage(Message message) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 474
   at StackExchange.Redis.RedisBase.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 45
   at StackExchange.Redis.RedisServer.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisServer.cs:line 626
   at StackExchange.Redis.RedisServer.FlushDatabaseAsync(Int32 database, CommandFlags flags) in /_/src/StackExchange.Redis/RedisServer.cs:line 253
   at EasyCaching.Redis.DefaultRedisCachingProvider.BaseFlushAsync(CancellationToken cancellationToken)
   at EasyCaching.Core.EasyCachingAbstractProvider.FlushAsync(CancellationToken cancellationToken)
```

## Specifications
- Provider    : EasyCaching.Redis (version 1.6.1)
- Interceptor : AspNet Core (version 6.0)
- Serializer  : EasyCaching.Serialization.Json (version 1.6.1)
- System      : Win10

**Comment by catcherwong** [comment]
@AntonioSCoelho Thanks for your interest in this project.

1. If you configure the option in you code

```cs
 option.UseRedis(config =>
                {
                    config.DBConfig.Endpoints.Add(new ServerEndPoint("127.0.0.1", 6379));
                    config.DBConfig.AllowAdmin = true;
                }, "redis1");
```

2. If you configure the option in you configuration file.

```cs
options.UseRedis(configuration);
```
```json
{
	"easycaching": {
		"redis": {
			"dbconfig": {				
				"AllowAdmin": true,
				"Endpoints": [{
					"Host": "127.0.0.1",
					"Port": 6739
				}]
			}
		}
	}
}
```

**Comment by AntonioSCoelho** [comment]
Thanks, it worked with the option on the JSON config.
